roll_pid:
  kp: 0.0025
  ki: 0.0
  kd: 0.0025
  clamp: 1.0
  inverted: False
  angular: True

pitch_pid:
  kp: 0.005
  ki: 0.00
  kd: 0.005
  clamp: 1.0
  inverted: False
  angular: True

heading_pid:
  kp: 0.0
  ki: 0.0
  kd: 0.0
  clamp: 0.4
  inverted: False
  angular: True

depth_pid:
  kp: 0.5
  ki: 0.00
  kd: 0.0
  clamp: 0.5
  inverted: False
  angular: False
